[build]
  base = "frontend"
  publish = "build"
  command = "echo 'Building...' && mkdir -p build && echo '<html><head><title>ServiceFix</title></head><body><h1>Site under maintenance</h1><p>We are currently updating our website. Please check back later.</p></body></html>' > build/index.html && chmod -R 755 build"

[build.environment]
  NODE_VERSION = "16.20.0"
  NPM_VERSION = "8.19.4"
  CI = "false"