[build]
  base = "frontend"
  publish = "build"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18.18.0"
  REACT_APP_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"