[build]
  base = "frontend"
  publish = "build"
  command = "npm install --force && npm install typescript@4.9.5 --no-save && GENERATE_SOURCEMAP=false REACT_APP_ENV=production npx --package=react-scripts@5.0.1 react-scripts build"

[build.environment]
  NODE_VERSION = "16.20.0"
  NPM_VERSION = "8.19.4"
  CI = "false" 