[build]
  base = "frontend"
  publish = "build"
  command = "CI= npm install --force && npm install typescript@4.9.5 --no-save && npm run build"

[build.environment]
  NODE_VERSION = "16.20.0"
  NPM_VERSION = "8.19.4"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_ENV = "production" 